import { useEffect, useRef, useState } from 'react'
import { DEFAULT_CHARACTER, characterPartRect, drawCharacter, type Accessory, type BottomStyle, type CharacterConfig, type CharacterMarkPart, type EyeStyle, type HairStyle, type HeadShape, type MouthStyle, type ShoeStyle, type TopStyle } from '../draw/characterKit'
import { loadCharacter, saveCharacter } from '../draw/customKid'
import { drawStrokes, simplifyStroke, INKS, type Stroke } from '../draw/strokes'
import { sfx } from '../audio/sfx'
import type { Part } from './characterParts'
const PARTS: Array<{ key: Part; label: string; hint: string }> = [
  { key: 'head', label: 'Head', hint: 'shape, width, height, tilt, skin' }, { key: 'hair', label: 'Hair', hint: 'form, color, scale, placement' },
  { key: 'face', label: 'Face', hint: 'eyes, expression, placement' }, { key: 'top', label: 'Top', hint: 'form, color, width, length' },
  { key: 'arms', label: 'Arms', hint: 'length and thickness' }, { key: 'bottoms', label: 'Bottoms', hint: 'form, color, width, length' },
  { key: 'legs', label: 'Legs', hint: 'length and thickness' }, { key: 'shoes', label: 'Shoes', hint: 'form, color, width, height' },
  { key: 'accessory', label: 'Extra', hint: 'type, color, size, placement' }, { key: 'mark', label: 'Draw on top', hint: 'a stable personal shirt mark' },
]
const SKINS = ['#f9e3c0', '#d8a47d', '#9a684c', '#704735', '#4a2d28']
const COLORS = ['#d95d39', '#4f8fb8', '#5c9645', '#e0a428', '#7a5b9a', '#33291f', '#fffdf4']
const pick = <T extends string>(label: string, value: T) => ({ label, value })
const HEADS = [pick('Round', 'round' as HeadShape), pick('Bean', 'bean'), pick('Soft square', 'soft-square')]
const HAIR = [pick('Sprigs', 'sprigs' as HairStyle), pick('Bob', 'bob'), pick('Swoop', 'swoop'), pick('Puffs', 'puffs'), pick('Cap', 'cap'), pick('Hood', 'hood')]
const EYES = [pick('Dots', 'dots' as EyeStyle), pick('Sleepy', 'sleepy'), pick('Sparkle', 'sparkle')]
const MOUTHS = [pick('Smile', 'smile' as MouthStyle), pick('Open smile', 'open'), pick('Freckles', 'freckles')]
const TOPS = [pick('Tee', 'tee' as TopStyle), pick('Jumper', 'jumper'), pick('Coat', 'coat'), pick('Dress', 'dress')]
const BOTTOMS = [pick('Shorts', 'shorts' as BottomStyle), pick('Pants', 'pants'), pick('Skirt', 'skirt'), pick('Overalls', 'overalls')]
const SHOES = [pick('Sneakers', 'sneakers' as ShoeStyle), pick('Boots', 'boots'), pick('Sandals', 'sandals')]
const EXTRAS = [pick('Nothing', 'none' as Accessory), pick('Backpack', 'backpack'), pick('Cape', 'cape'), pick('Bow', 'bow'), pick('Scarf', 'scarf')]

function Choice<T extends string>({ title, value, choices, set }: { title: string; value: T; choices: { label: string; value: T }[]; set: (value: T) => void }) { return <section className="direct-control"><h3>{title}</h3><div className="direct-options">{choices.map((choice) => <button key={choice.value} className={choice.value === value ? 'selected' : ''} onClick={() => set(choice.value)}>{choice.label}</button>)}</div></section> }
function Colors({ title, value, colors = COLORS, set }: { title: string; value: string; colors?: string[]; set: (value: string) => void }) { return <section className="direct-control"><h3>{title}</h3><div className="direct-colors">{colors.map((color) => <button key={color} aria-label={`${title}: ${color}`} className={color === value ? 'selected' : ''} style={{ background: color }} onClick={() => set(color)} />)}</div></section> }
function Dial({ title, value, set, min = .62, max = 1.48, step = .03, signed = false }: { title: string; value: number; set: (value: number) => void; min?: number; max?: number; step?: number; signed?: boolean }) { const shown = signed ? `${value > 0 ? '+' : ''}${Math.round(value * (Math.abs(value) < 1 ? 100 : 1))}` : `${Math.round(value * 100)}%`; return <label className="direct-dial"><span>{title}<output>{shown}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => set(Number(event.target.value))} /></label> }

function PaperDoll({ config, selected, select, facing, setFacing, markColor, markSize, setMarks }: { config: CharacterConfig; selected: Part; select: (part: Part) => void; facing: 'front'|'side'|'back'; setFacing:(facing:'front'|'side'|'back')=>void; markColor:string; markSize:number; setMarks:(part: CharacterMarkPart, marks: Stroke[])=>void }) {
  const canvas = useRef<HTMLCanvasElement>(null), live = useRef<Stroke | null>(null)
  const drawable = ['hair','face','top','bottoms','shoes','accessory'].includes(selected) ? selected as CharacterMarkPart : null
  const marks = drawable ? config.marks[drawable]?.[facing] ?? (drawable==='top' && facing==='front' ? config.patch : []) : []
  useEffect(() => { const ctx = canvas.current?.getContext('2d'); if (!ctx) return; ctx.clearRect(0,0,300,300); drawCharacter(ctx, config, facing, 0); if (live.current && drawable) { const r=characterPartRect(drawable,facing); ctx.save();ctx.translate(r.x,r.y);ctx.scale(r.w,r.h);drawStrokes(ctx,[live.current],1);ctx.restore() } }, [config, facing, drawable, marks, markColor, markSize])
  const point = (event:React.PointerEvent):number[]|null => { if(!drawable)return null;const r=characterPartRect(drawable,facing);if(!r.w||!r.h)return null;const box=canvas.current!.getBoundingClientRect(),x=(event.clientX-box.left)/box.width*300,y=(event.clientY-box.top)/box.height*300;if(x<r.x||x>r.x+r.w||y<r.y||y>r.y+r.h)return null;return [(x-r.x)/r.w,(y-r.y)/r.h,event.pressure||.6] }
  const down=(event:React.PointerEvent)=>{const p=point(event);if(!p)return;canvas.current!.setPointerCapture(event.pointerId);live.current={pts:[p],size:markSize,color:markColor};};const move=(event:React.PointerEvent)=>{if(!live.current)return;const p=point(event);if(!p)return;live.current.pts.push(p);const ctx=canvas.current?.getContext('2d');if(ctx&&drawable){const r=characterPartRect(drawable,facing);ctx.clearRect(0,0,300,300);drawCharacter(ctx,config,facing,0);ctx.save();ctx.translate(r.x,r.y);ctx.scale(r.w,r.h);drawStrokes(ctx,[...marks,live.current],1);ctx.restore()}};const up=()=>{if(!live.current||!drawable)return;const stroke={...live.current,pts:simplifyStroke(live.current.pts)};live.current=null;setMarks(drawable,[...marks,stroke])}
  return <section className="doll-stage"><div className="doll-stage-head"><div><p className="eyebrow">Click a part to edit it</p><h3>Original island kid, directly editable</h3></div><div className="facing-toggle">{(['front','side','back'] as const).map((view) => <button key={view} className={facing === view ? 'selected' : ''} onClick={() => setFacing(view)}>{view}</button>)}</div></div><div className={`doll-canvas ${drawable ? 'is-drawing' : ''}`}><canvas ref={canvas} width="300" height="300" aria-label="Editable character preview" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/>{PARTS.filter((part) => part.key !== 'mark').map((part) => <button key={part.key} className={`part-hit part-${part.key} ${selected === part.key ? 'selected' : ''}`} onClick={() => select(part.key)} aria-label={`Edit ${part.label}`}><span>{part.label}</span></button>)}</div><p className="part-readout"><strong>{PARTS.find((part) => part.key === selected)?.label}</strong> — {drawable ? `draw directly on this ${facing} view, then use the controls to keep its island-kid style.` : PARTS.find((part) => part.key === selected)?.hint}</p></section>
}
export function CharacterStudio({ onDone }: { onDone: () => void }) {
  const [config, setConfig] = useState<CharacterConfig>(() => loadCharacter()), [selected, setSelected] = useState<Part>('head'), [facing, setFacing] = useState<'front'|'side'|'back'>('front'), [markColor, setMarkColor] = useState('ink'), [markSize, setMarkSize] = useState(.035)
  const set = <K extends keyof CharacterConfig>(key: K, value: CharacterConfig[K]) => setConfig((current) => ({...current,[key]:value}))
  const inspector = (() => { switch(selected) {
    case 'head': return <><Choice title="Head form" value={config.headShape} choices={HEADS} set={(v)=>set('headShape',v)}/><Colors title="Skin" value={config.skin} colors={SKINS} set={(v)=>set('skin',v)}/><Dial title="Width" value={config.headWidth} set={(v)=>set('headWidth',v)}/><Dial title="Height" value={config.headHeight} set={(v)=>set('headHeight',v)}/><Dial title="Tilt" value={config.headTilt} min={-.24} max={.24} step={.01} signed set={(v)=>set('headTilt',v)}/></>
    case 'hair': return <><Choice title="Hair form" value={config.hair} choices={HAIR} set={(v)=>set('hair',v)}/><Colors title="Hair color" value={config.hairColor} set={(v)=>set('hairColor',v)}/><Dial title="Width" value={config.hairWidth} set={(v)=>set('hairWidth',v)}/><Dial title="Height" value={config.hairHeight} set={(v)=>set('hairHeight',v)}/><Dial title="Left / right" value={config.hairOffsetX} min={-24} max={24} step={1} signed set={(v)=>set('hairOffsetX',v)}/><Dial title="Up / down" value={config.hairOffsetY} min={-24} max={24} step={1} signed set={(v)=>set('hairOffsetY',v)}/></>
    case 'face': return <><Choice title="Eyes" value={config.eyes} choices={EYES} set={(v)=>set('eyes',v)}/><Choice title="Expression" value={config.mouth} choices={MOUTHS} set={(v)=>set('mouth',v)}/><Dial title="Eye spacing" value={config.eyeSpacing} set={(v)=>set('eyeSpacing',v)}/><Dial title="Eye size" value={config.eyeSize} set={(v)=>set('eyeSize',v)}/><Dial title="Eye height" value={config.eyeY} set={(v)=>set('eyeY',v)}/></>
    case 'top': return <><Choice title="Top form" value={config.top} choices={TOPS} set={(v)=>set('top',v)}/><Colors title="Top color" value={config.topColor} set={(v)=>set('topColor',v)}/><Dial title="Width" value={config.torsoWidth} set={(v)=>set('torsoWidth',v)}/><Dial title="Length" value={config.topLength} set={(v)=>set('topLength',v)}/></>
    case 'arms': return <><Dial title="Arm length" value={config.armLength} set={(v)=>set('armLength',v)}/><Dial title="Arm thickness" value={config.armThickness} set={(v)=>set('armThickness',v)}/></>
    case 'bottoms': return <><Choice title="Bottom form" value={config.bottoms} choices={BOTTOMS} set={(v)=>set('bottoms',v)}/><Colors title="Bottom color" value={config.bottomColor} set={(v)=>set('bottomColor',v)}/><Dial title="Width" value={config.bottomWidth} set={(v)=>set('bottomWidth',v)}/><Dial title="Length" value={config.bottomLength} set={(v)=>set('bottomLength',v)}/></>
    case 'legs': return <><Dial title="Leg length" value={config.legLength} set={(v)=>set('legLength',v)}/><Dial title="Leg thickness" value={config.legThickness} set={(v)=>set('legThickness',v)}/></>
    case 'shoes': return <><Choice title="Shoe form" value={config.shoes} choices={SHOES} set={(v)=>set('shoes',v)}/><Colors title="Shoe color" value={config.shoeColor} set={(v)=>set('shoeColor',v)}/><Dial title="Width" value={config.shoeWidth} set={(v)=>set('shoeWidth',v)}/><Dial title="Height" value={config.shoeHeight} set={(v)=>set('shoeHeight',v)}/></>
    case 'accessory': return <><Choice title="Extra" value={config.accessory} choices={EXTRAS} set={(v)=>set('accessory',v)}/><Colors title="Extra color" value={config.accessoryColor} set={(v)=>set('accessoryColor',v)}/><Dial title="Size" value={config.accessoryScale} set={(v)=>set('accessoryScale',v)}/><Dial title="Left / right" value={config.accessoryX} min={-24} max={24} step={1} signed set={(v)=>set('accessoryX',v)}/><Dial title="Up / down" value={config.accessoryY} min={-24} max={24} step={1} signed set={(v)=>set('accessoryY',v)}/></>
    default:return null
  } })()
  const drawablePart: CharacterMarkPart | null = ['hair', 'face', 'top', 'bottoms', 'shoes', 'accessory'].includes(selected) ? selected as CharacterMarkPart : selected === 'mark' ? 'top' : null
  const setLocalMarks = (part: CharacterMarkPart, marks: Stroke[]) => setConfig((current) => ({ ...current, patch: part === 'top' && facing === 'front' ? marks : current.patch, marks: { ...current.marks, [part]: { ...current.marks[part], [facing]: marks } } }))
  return <div className="table-veil"><div className="sheet direct-character-studio"><header className="sheet-head"><button className="btn ghost" onClick={onDone}>cancel</button><div><p className="eyebrow">Character workbench</p><h2>Click the kid. Shape the part.</h2></div><button className="btn confirm" onClick={()=>{saveCharacter(config);sfx.chime();onDone()}}>Use this character</button></header><p className="workbench-intro">The original paper kid is the editable master sheet. Pick a visible part, change only that part, and check front, side, and back before you save.</p><div className="direct-workspace"><nav className="part-rail" aria-label="Character parts">{PARTS.map((part)=><button key={part.key} className={selected===part.key?'selected':''} onClick={()=>setSelected(part.key)}><strong>{part.label}</strong><small>{part.hint}</small></button>)}</nav><PaperDoll config={config} selected={selected} select={setSelected} facing={facing} setFacing={setFacing} markColor={markColor} markSize={markSize} setMarks={setLocalMarks}/><aside className="part-inspector"><div className="inspector-head"><p className="eyebrow">Editing · {facing} view</p><h3>{PARTS.find((part)=>part.key===selected)?.label}</h3></div>{inspector}{drawablePart && <section className="direct-control draw-on-part"><h3>Draw directly on this part</h3><p>Your mark stays attached to the visible {facing} {drawablePart}.</p><div className="mark-tools">{[.02,.035,.055].map((value)=><button key={value} className={`tool-dot ${markSize===value?'on':''}`} onClick={()=>setMarkSize(value)} aria-label={`Line size ${value}`}><span style={{width:6+value*210,height:6+value*210}} /></button>)}{Object.entries(INKS).map(([key,hex])=><button key={key} className={`ink ${markColor===key?'on':''}`} style={{background:hex}} onClick={()=>setMarkColor(key)} aria-label={key}/>)}</div><button className="btn ghost small" disabled={!(config.marks[drawablePart]?.[facing] ?? []).length} onClick={()=>setLocalMarks(drawablePart,(config.marks[drawablePart]?.[facing] ?? []).slice(0,-1))}>Undo mark</button><button className="btn ghost small" disabled={!(config.marks[drawablePart]?.[facing] ?? []).length} onClick={()=>setLocalMarks(drawablePart,[])}>Clear mark</button></section>}<button className="btn ghost small reset-workbench" onClick={()=>setConfig({...DEFAULT_CHARACTER,patch:[],marks:{}})}>Reset to original kid</button></aside></div></div></div>
}
